// <auto-generated />
namespace HNStationaryStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateNews));
        
        string IMigrationMetadata.Id
        {
            get { return "202504021504315_updateNews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
