// <auto-generated />
namespace HNStationaryStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateemail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateemail));
        
        string IMigrationMetadata.Id
        {
            get { return "202504241607157_update-email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
